### ISSUE TITLE
Tidslinje - ferdig prosjekt og utviklingsløype

### ISSUE THREAD

**Issue by Robinzki** [NetcodeAS/kontor-leie#14]

**Comment by oleterno** [comment]
Skrev om at vi har valgt å vise fremdriften i prosjektet på en tidslinje fremfor å bruke Gantt-diagram.

**Comment by oleterno** [comment]
La inn tidslinjen slik den er nå. Dersom tidslinjen endres senere er det bare å oppdatere bildet i dokumentet.

**Comment by oleterno** [comment]
https://www.gantt.com/
