### ISSUE TITLE
Utforske forskjellige betalingsløsninger

### ISSUE THREAD

**Issue by Robinzki** [NetcodeAS/kontor-leie#3]
Utforske Woocommerce, er dette noe for dette prosjektet?

**Comment by oleterno** [comment]
Skriver om fordeler og ulemper med de ulike betalingsløsningene

**Comment by Kristoball** [comment]
Vi så på WooCommerce og hvordan vi kan tilpasse det. Er en del vi må sette oss inn i av både woocommerce og word-press api. 
#6

**Comment by miiik4** [comment]
Følges opp senere i rapporten.
